### ISSUE TITLE
Doc update for flexible classroom

### ISSUE THREAD

**Issue by pmmgithub** [AgoraIO/Docs-Source#1172] opened 2023-02-07 08:19 UTC
Hi, the following request is from FCR product manager, please help clarity, thanks!
https://docs.agora.io/en/flexible-classroom/get-started/?platform=android#references 
below red highlight link is not working, could you please point out? i am also not able to find this in CN doc. 
![image](https://user-images.githubusercontent.com/45590614/217189973-dfb5ebcf-3714-4083-aad4-92a99fa04ee9.png)

**Comment by nirm2009** [comment] 2023-09-14 16:31
Hi @pmmgithub, I'm having trouble reproducing the mentioned issue. I checked and the [UI Builder quickstart](https://docs.agora.io/en/flexible-classroom/get-started/get-started-uiavbuilder) link seems to work on all platforms in https://docs.agora.io/en/flexible-classroom/get-started. The link fix must have already been applied by another commit. Could you please help verify this?

**Comment by nirm2009** [comment] 2023-12-07 21:17
Closing this ticket due to lack of reply. Please feel free to open a new ticket if there is still something to be done.

**Closed by nirm2009** 2023-12-07 21:17 UTC
