### ISSUE TITLE
Spatial Audio Off Billing

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#923] opened 2022-11-25 10:29 UTC
**Business case**: How will this issue help our customers.

**Subject Matter Expert**: fengshengyuan@agora.io

**Reviewers**:
  - *Technical*: 
  - *Language*: Iain
  - *PM*: only if essential

**Scope**: No info, but I think this is to do with pricing for this feature. See, 

**Acceptance criteria**: Pricing must be correct and easy to understand.

**Additional valuable information**: Branches for all tickets must be merged to https://github.com/AgoraIO/Docs-Source/tree/milestone40-web4.16.0

**Comment by atovpeko** [comment] 2023-01-09 16:30
Duplicate of https://github.com/AgoraIO/Docs-Source/issues/941

**Closed by atovpeko** 2023-01-09 16:30 UTC
