### ISSUE TITLE
Multi terminal login

### ISSUE THREAD

**Issue by pmzcnmb1** [AgoraIO/Docs-Source#1450] opened 2023-08-24 02:58 UTC

**Comment by pmzcnmb1** [comment] 2023-08-24 03:01
Does it support simultaneous login from multiple terminals?

**Comment by atovpeko** [comment] 2023-10-05 18:09
@pmzcnmb1 I'll close this ticket since there is no input. Please feel free to open a new one if the issue is not resolved. Thank you :-)

**Closed by atovpeko** 2023-10-05 18:09 UTC
