### ISSUE TITLE
Signature does not match documentation

### ISSUE THREAD

**Issue by MetaSeth** [AgoraIO/Docs-Source#1504] opened 2023-12-07 09:03 UTC
### Platform

Web

### Platform details

I'm only using the web product, but i guess it could be on others platform too.

### Product

Video Calling

### Product details

RtcTokenBuilder.buildTokenWithUid signature

### Business Case

Simpler for new users

### Subject Matter Expert

`RtcTokenBuilder.buildTokenWithUid()` expects 6 arguments, but only 5 are provided in the documentation. The `token_expire` argument is missing in the example.

Should be something like that:
```javascript
const expirationTimeInSeconds = 3600;
const tokenA =RtcTokenBuilder.buildTokenWithUid(appID, appCertificate, channelName, uid, role, tokenExpirationInSecond, privilegeExpiredTs);
```

### Documentation Link

https://docs.agora.io/en/video-calling/develop/integrate-token-generation?platform=web#implement-token-generation

### Acceptance Criteria

The documentation update should be technicaly accurate.

Edit: 
I made a mistake when describing the error.
It was `Expected 7 arguments, but got 6.ts(2554) 
index.d.ts(26, 159): An argument for 'privilege_expire' was not provided.`
I have posted an example.

**Comment by Kishan-Dhakan** [comment] 2023-12-14 09:31
The doc at https://docs.agora.io/en/video-calling/develop/integrate-token-generation?platform=web#implement-token-generation seems to be working fine for me. Could you share steps to reproduce or your code?
@saudsami there was an unrelated issue that I have fixed in https://github.com/AgoraIO/Doc-Source-Private/pull/818

**Comment by MetaSeth** [comment] 2023-12-20 13:34
Here a little [repo](https://github.com/MetaSeth/agoraTest) showing the issue

**Comment by Kishan-Dhakan** [comment] 2024-01-05 07:46
Fixed by https://github.com/AgoraIO/Doc-Source-Private/pull/870. @MetaSeth this will updated in the next publish. For your use, you may use the correct code:

```
const tokenA = RtcTokenBuilder.buildTokenWithUid(
      appId,
      appCertificate,
      channelName,
      uid,
      role,
      expirationTimeInSeconds,
      privilegeExpiredTs
    );

const tokenB = RtcTokenBuilder.buildTokenWithUserAccount(
    appId,
    appCertificate,
    channelName,
    userAccount,
    role, 
    privilegeExpiredTs);
```

**Closed by Kishan-Dhakan** 2024-01-05 07:46 UTC
