### ISSUE TITLE
https://docs-staging.agora.io/en/help/general-product-inquiry/capacity/

### ISSUE THREAD

**Issue by timin1970** [AgoraIO/Docs-Source#500] opened 2022-09-29 19:04 UTC
bullet formatting is off

@billy-the-fish

**Comment by Kishan-Dhakan** [comment] 2022-10-03 07:14
Hmm, this seems to be a duplicate of https://github.com/AgoraIO/Docs-Source/issues/499. It will be resolved in https://github.com/AgoraIO/Docs-Help/pull/5.

**Closed** 2022-10-07 13:59 UTC
