### ISSUE TITLE
Release notes, API refs and version numbers

### ISSUE THREAD

**Issue by billy-the-fish** [AgoraIO/Docs-Source#1036] opened 2022-12-19 10:30 UTC
**Business case**: How will this issue help our customers.

**Reviewers**:
  - *Technical*: Kyle
  - *Language*: Iain
  - *PM*: 

**Scope**: Updates to the following:
 - Release notes: https://docs.agora.io/en/flexible-classroom/reference/release-notes, source to be supplied by CN team. 
 - API reference: for Classroom SDK API,  Proctor SDK API, Classroom REST API.  Source to be supplied by CN team
 - Version numbers and links to binaries in the doc build. 

**Acceptance criteria**: Docs must be technically correct and follow the google style guide. 

**Additional valuable information**: All branches must be made from and merged to: https://github.com/AgoraIO/Docs-Source/tree/milestone44-flexible-classroom-2.8.0

**Comment by atovpeko** [comment] 2022-12-27 13:08
Duplicate of https://github.com/AgoraIO/Docs-Source/issues/1056

**Closed by atovpeko** 2022-12-27 13:08 UTC
